def register(label):
    for key,ru,en in [
        ('compare.action','Сравнить','Compare'),
        ('compare.title','Сравнение экипировки','Equipment comparison'),
        ('compare.owner','Владелец: %s','Owner: %s'),
        ('compare.creature_owner','Предметы существ — выбранный владелец:','Creature held items — selected owner:'),
        ('compare.trainer_name','Хранительница','Ranger'),
        ('compare.trainer','Для хранительницы','For the ranger'),
        ('compare.current','Сейчас надето','Currently equipped'),
        ('compare.candidate','После замены','After replacement'),
        ('compare.empty','Слот свободен','Empty slot'),
        ('compare.context','Изменения с учётом черт, экипировки и текущих эффектов','Changes include traits, equipment and current effects'),
        ('compare.no_stats','Числовые характеристики не меняются. Сравните свойства предметов выше.','No stat changes. Compare the item effects above.'),
        ('compare.projectiles','Целей снарядами: %d → %d','Projectile targets: %d → %d'),
        ('compare.chains','Скачков цепи: %d → %d','Chain jumps: %d → %d'),
        ('compare.ability','Урон: %.1f → %.1f · перезарядка: %.2f → %.2f с','Damage: %.1f → %.1f · cooldown: %.2f → %.2f s'),
        ('compare.ability_note','Урон до защиты цели и критических ударов. Текущая перезарядка при замене сохраняется.','Damage before target defense and critical hits. Equipping preserves the current recharge timer.'),
        ('compare.back','← Рюкзак','← Inventory'),
        ('compare.equip','Надеть выбранный предмет','Equip selected item'),
        ('compare.remove','Снять: %s','Unequip: %s'),
        ('compare.full','В рюкзаке нет места. Предмет остаётся надетым.','Inventory is full. The item stays equipped.'),
        ('status.title','Состояние и эффекты','Condition and effects'),
        ('status.inspect','Эффекты: %d','Effects: %d'),
        ('status.paused','Бой приостановлен. Tab / Shift+Tab — переход между эффектами и владельцем. Esc — вернуться в бой.','Combat is paused. Tab / Shift+Tab — browse effects and owner. Esc — return to combat.'),
        ('status.shield','Щит','Shield'),
        ('status.target','Цель: %s','Target: %s'),
        ('status.vitals','Здоровье %.1f / %.1f · щит %.1f · энергия %.1f','Health %.1f / %.1f · shield %.1f · energy %.1f'),
        ('status.empty','Активных эффектов нет','No active effects'),
        ('hud.shield_detail','Щит: %.1f. Поглощает входящий урон раньше здоровья.','Shield: %.1f. Absorbs incoming damage before health.'),
        ('hud.effect_expired','Эффект завершился.','This effect has expired.'),
        ('hud.inspect_hint','Нажмите значок или откройте «Состояние и эффекты» в меню Esc. Tab / Shift+Tab — переход между эффектами.','Click an icon or open Condition and effects in the Esc menu. Tab / Shift+Tab — browse effects.'),
        ('status.remaining','Осталось %.1f с · зарядов %d / %d','%.1f s remaining · stacks %d / %d'),
        ('status.tick','Следующий тик через %.2f с · осталось тиков: %d','Next tick in %.2f s · ticks remaining: %d'),
        ('status.damage','Урон за тик: %.1f, критический: %.1f. Учтены защита и типы; щит и блокирование урона не учтены.','Damage per tick: %.1f, critical: %.1f. Includes defense and types; excludes shields and damage blocking.'),
        ('status.no_damage','Этот эффект сейчас не наносит периодический урон.','This effect currently deals no periodic damage.'),
        ('status.damage_no_crit','Урон за тик: %.1f. Критический удар невозможен. Учтены защита и типы; щит и блокирование урона не учтены.','Damage per tick: %.1f. Cannot critically hit. Includes defense and types; excludes shields and damage blocking.'),
        ('status.reaction_chain','Реакция с типом «%s»: +%d скачков цепи; эффект расходуется.','Reaction with %s: +%d chain jumps; consumes this effect.'),
        ('status.reaction_bonus','Реакция с типом «%s»: урон удара ×%.2f; эффект расходуется.','Reaction with %s: hit damage ×%.2f; consumes this effect.'),
        ('element.fire','Огонь','Fire'),('element.water','Вода','Water'),
        ('element.nature','Природа','Nature'),('element.electric','Электричество','Electric'),('element.neutral','Нейтральный','Neutral')
    ]: label(key,ru,en)
