"""Player-facing menus and runtime messages. Stable keys also cover formatted text."""

STRINGS = [
    ('demo.scope', 'Демо · Тихая гавань и Янтарная роща. Выполните три задачи и освободите рощу.', 'Demo · Stillwater Haven and the Amber Grove. Complete three objectives and free the grove.'),
    ('demo.results', 'Итоги демо', 'Demo results'),
    ('demo.title', 'Роща снова дышит', 'The grove breathes again'),
    ('demo.subtitle', 'Демонстрационное путешествие завершено', 'Demo journey complete'),
    ('demo.story', 'Вы приручили дикое существо, одолели элитного стража и освободили древнюю рощу. Свет фонаря снова согревает её корни.', 'You tamed a wild creature, defeated the elite guardian and freed the ancient grove. The lantern’s light warms its roots once more.'),
    ('demo.after', 'Можно продолжить исследование и забрать оставшуюся добычу. В лагере доступна новая экспедиция. При выходе путешествие сохранится.', 'You can keep exploring and collect any remaining loot. Start another expedition at camp. Your journey will be saved when you quit.'),
    ('demo.explore', 'Продолжить исследование', 'Keep exploring'),
    ('app.title', 'Emberwild — Хранители рощи', 'Emberwild — Guardians of the Grove'),
    ('hud.level', 'Ур. %s · %s%%', 'Lv. %s · %s%%'),
    ('hud.health', 'ХРАНИТЕЛЬНИЦА   %d / %d', 'RANGER   %d / %d'),
    ('hud.resources', '◈ %d   ·   Печати %d', '◈ %d   ·   Seals %d'),
    ('hud.objectives', 'ПАМЯТЬ РОЩИ\n%s Поймайте дикое существо\n%s Победите элитного стража\n%s Освободите древнюю рощу', 'MEMORY OF THE GROVE\n%s Capture a wild creature\n%s Defeat the elite guardian\n%s Free the ancient grove'),
    ('hud.capture', 'Захват', 'Capture'),
    ('hud.cooldown', '%.1f с', '%.1f s'),
    ('menu.tagline', 'Х Р А Н И Т Е Л И   Р О Щ И', 'G U A R D I A N S   O F   T H E   G R O V E'),
    ('menu.intro', 'Древняя роща гаснет. Зажгите её вновь.\nИсследуйте лес, приручайте существ и создайте свою команду.', 'The ancient grove is fading. Rekindle its light.\nExplore the forest, tame creatures and build your party.'),
    ('menu.start', 'Начать путешествие', 'Begin journey'),
    ('menu.continue', 'Продолжить', 'Continue'),
    ('menu.settings', 'Настройки', 'Settings'),
    ('menu.paused', 'Путешествие приостановлено', 'Journey paused'),
    ('menu.pause_hint', 'Янтарный свет подождёт вашего возвращения', 'The amber light will await your return'),
    ('menu.party', 'Команда', 'Party'),
    ('menu.inventory', 'Рюкзак', 'Inventory'),
    ('menu.save', 'Сохранить', 'Save'),
    ('menu.load', 'Загрузить', 'Load'),
    ('menu.quit', 'Выход с сохранением', 'Save and quit'),
    ('menu.close', 'Закрыть', 'Close'),
    ('inventory.hint', 'Предметы меняют возможности команды. Выберите владельца перед экипировкой.', 'Items change your party’s abilities. Choose an owner before equipping.'),
    ('item.rarity.0', 'Обычный', 'Common'),
    ('item.rarity.1', 'Магический', 'Magic'),
    ('item.rarity.2', 'Редкий', 'Rare'),
    ('item.rarity.3', 'Уникальный', 'Unique'),
    ('inventory.equip', 'Надеть', 'Equip'),
    ('inventory.empty', 'Рюкзак пуст. Редкие находки ждут в роще.', 'Your inventory is empty. Rare finds await in the grove.'),
    ('party.title', 'Ваша команда', 'Your party'),
    ('party.progress', 'Уровень %d · %d / %d XP · %d%% HP', 'Level %d · %d / %d XP · %d%% HP'),
    ('party.active', 'В БОЮ', 'ACTIVE'),
    ('party.slot', 'В слот %d', 'To slot %d'),
    ('party.evolve', 'Эволюция', 'Evolve'),
    ('settings.hint', 'Декоративные эффекты можно уменьшить. Предупреждения атак остаются видимыми.', 'You can reduce decorative effects. Attack warnings remain visible.'),
    ('settings.quality.0', 'Эффекты: низкие', 'Effects: low'),
    ('settings.quality.1', 'Эффекты: средние', 'Effects: medium'),
    ('settings.quality.2', 'Эффекты: высокие', 'Effects: high'),
    ('settings.shake', 'Встряска камеры', 'Camera shake'),
    ('settings.fullscreen', 'Полный экран', 'Fullscreen'),
    ('settings.language', 'Язык', 'Language'),
    ('audio.Master', 'Общая громкость', 'Master volume'),
    ('audio.Music', 'Музыка', 'Music'),
    ('audio.SFX', 'Звуки', 'Sound effects'),
    ('audio.UI', 'Интерфейс', 'Interface'),
    ('audio.Ambience', 'Окружение', 'Ambience'),
    ('audio.Voice', 'Голоса', 'Voices'),
    ('camp.title', 'Лагерь хранителей', 'Guardians’ camp'),
    ('camp.hint', 'Покупайте припасы и оставляйте находки в тайнике.', 'Buy supplies and leave your finds in the stash.'),
    ('camp.currency', 'Янтарь: %d', 'Amber: %d'),
    ('camp.seals', '3 печати · 15 янтаря', '3 seals · 15 amber'),
    ('camp.potions', '2 лечебных настоя · 12 янтаря', '2 healing draughts · 12 amber'),
    ('camp.stash', 'В тайник: %s', 'Stash: %s'),
    ('camp.take', 'Забрать: %s', 'Take: %s'),
    ('camp.expedition', 'Новая экспедиция · обновить рощу', 'New expedition · reset the grove'),
    ('defeat.title', 'Фонарь ещё горит', 'The lantern still burns'),
    ('defeat.hint', 'Источник в гавани восстановит вас и вашу команду.', 'The spring in the haven will restore you and your party.'),
    ('defeat.return', 'Вернуться в гавань', 'Return to the haven'),
    ('debug.title', 'Инструменты разработчика', 'Developer tools'),
    ('debug.stats', 'seed %d · %.1f DPS · %d событий', 'seed %d · %.1f DPS · %d events'),
    ('debug.help', 'help — список команд', 'help — list commands'),
    ('debug.collision', 'Показать / скрыть коллизии и AI', 'Toggle collisions and AI'),
    ('debug.seed', 'Скопировать seed', 'Copy seed'),
    ('debug.stress', 'Нагрузка: 30 противников', 'Stress: 30 enemies'),
    ('notice.saved', 'Путешествие сохранено', 'Journey saved'),
    ('notice.missing_save', 'Сохранение не найдено или повреждено', 'Save not found or damaged'),
    ('notice.empty_party', 'В сохранении нет допустимых существ', 'The save contains no valid creatures'),
    ('notice.loaded', 'Путешествие восстановлено', 'Journey restored'),
    ('notice.equipped', 'Экипировано: %s', 'Equipped: %s'),
    ('notice.defeated', '%s без сил. Смените существо или вернитесь к источнику.', '%s is exhausted. Swap creatures or return to the spring.'),
    ('notice.victory', 'Роща свободна! Корень первозданных — ваша награда.', 'The grove is free! The Primordial Root is your reward.'),
    ('notice.level', '%s · уровень %d', '%s · level %d'),
    ('notice.mode', 'Команда: %s', 'Party: %s'),
    ('mode.0', 'Атака', 'Aggressive'),
    ('mode.1', 'Защита', 'Defensive'),
    ('mode.2', 'Следовать', 'Follow'),
    ('mode.3', 'Держать позицию', 'Hold position'),
    ('notice.ability_unavailable', 'Способность ещё не готова или цель слишком далеко', 'Ability not ready or target out of range'),
    ('notice.swap_unavailable', 'Смена недоступна: существо активно, без сил или идёт перезарядка', 'Cannot swap: the creature is active, exhausted or swap is recharging'),
    ('notice.capture_target', 'Подойдите к дикому существу и ослабьте его', 'Approach a wild creature and weaken it'),
    ('notice.capture_unavailable', 'Нет печатей, команда заполнена или цель не поддаётся захвату', 'No seals, party full or target cannot be captured'),
    ('notice.joined', '%s присоединяется к команде!', '%s joins your party!'),
    ('notice.escaped', 'Существо вырвалось · шанс был %d%%', 'The creature escaped · chance was %d%%'),
    ('notice.received', 'Получено: %s', 'Received: %s'),
    ('notice.full', 'Рюкзак заполнен', 'Inventory full'),
    ('notice.rested', 'Источник восстановил команду', 'The spring restored your party'),
    ('notice.phase', 'Страж пробуждается · Фаза %d', 'The guardian awakens · Phase %d'),
    ('notice.reserve_defeated', '%s без сил в резерве', '%s is exhausted in reserve'),
    ('save.invalid_structure', 'Недопустимая структура сохранения', 'Invalid save structure'),
    ('save.too_large', 'Сохранение превышает допустимый размер', 'Save exceeds the supported size limit'),
    ('save.read_failed', 'Не удалось прочитать сохранение (код %d)', 'Cannot read save (code %d)'),
    ('save.invalid_journey', 'В сохранении недопустимая команда, экипировка или отсутствующий контент. Текущее путешествие не изменено.', 'The save has an invalid party, equipment or unavailable content. Your current journey was not changed.'),
    ('save.exit_failed', 'Игра остаётся открытой: сохранить путешествие не удалось. Исправьте причину и повторите сохранение.', 'The game remains open because your journey could not be saved. Resolve the problem and try saving again.'),
    ('save.travel_busy', 'Дождитесь завершения перехода между областями.', 'Wait for the area transition to finish.'),
    ('save.recovered', 'Путешествие восстановлено из резервной копии. Самые последние изменения могут отсутствовать.', 'Journey restored from the backup. The most recent changes may be missing.'),
    ('save.write_failed', 'Не удалось записать сохранение (код %d)', 'Cannot write save (code %d)'),
    ('save.backup_failed', 'Не удалось создать копию сохранения (код %d)', 'Cannot back up save (code %d)'),
    ('save.commit_failed', 'Не удалось завершить сохранение (код %d)', 'Cannot commit save (code %d)'),
    ('save.invalid_json', 'Повреждён файл сохранения: %s', 'Invalid save JSON: %s'),
    ('save.invalid_version', 'Некорректная версия сохранения', 'Invalid save version'),
    ('save.unsupported_version', 'Неподдерживаемая версия сохранения: %d', 'Unsupported save version: %d'),
]


def register(label):
    for key, ru, en in STRINGS:
        label(key, ru, en)
